version: "3.9"

services:
  ui:
    # image: openinfolabs/osintbuddy-frontend:latest
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: "${BASE_URL}"
        NODE_ENV: "${ENVIRONMENT}"
    volumes:
      - ./frontend/:/app/
    ports:
      - "${FRONTEND_PORT-.env FRONTEND_PORT needs to be set}:80"
    env_file:
      - .env
  backend:
    # image: openinfolabs/osintbuddy-backend:latest
    command: ["/bin/sh", "-c", "./start-reload.sh"]
    build:
      context: ./backend/backend
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend/backend/app:/app/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "${BACKEND_PORT-8000}:80"
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT-6379}:6379"
    command: redis-server
  db:
    image: "${POSTGRES_IMAGE-postgres:16.0}"
    volumes:
      - "osintbuddy-db-data:${PGDATA-/var/lib/postgresql/data/pgdata}"
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT-5432}:5432"
  janus:
    build:
      context: ./cfg/janus
      dockerfile: janusgraph.Dockerfile
    ports:
      - "8182:8182"
    volumes:
      - "./cfg/janus/janusgraph-dynamic.properties:/opt/janusgraph/janusgraph-dynamic.properties"
      - "./cfg/janus/janusgraph-server.yaml:/etc/opt/janusgraph/janusgraph-server.yaml"
      - "./cfg/janus/empty-sample.groovy:/opt/janusgraph/scripts/empty-sample.groovy"
  sdb:
    image: scylladb/scylla:5.1
    ports:
      - "${SDB_REST_PORT-10000}:10000"
      - "${CQL_PORT-9042}:9042"
      - "${THRIFT_PORT-9160}:9160"
      - "${INTERNODE_PORT-7000}:7000"
      - "${INTERNODE_ONE_PORT-7001}:7001"
      - "${JMX_PORT-7199}:7199"
    env_file:
      - .env
    volumes:
      - sdb-data:${SCYLLADATA-/var/lib/scylla}
  index:
    image: "solr:9.3.0-slim"
    volumes:
      - solr-data:/var/solr
    ports:
      - "${SOLR_PORT-8983}:8983"
    env_file:
      - .env
  worker:
    # image: openinfolabs/osintbuddy-worker:latest
    command: /worker-start.sh
    build:
      context: ./backend/backend
      dockerfile: worker.Dockerfile
    env_file:
      - .env
  clearly:
    image: rsalmei/clearly:latest
    ports:
      - "${CLEARLY_PORT-12223}:12223"
    command:
      - "server $(CELERY_BROKER_URL) --backend "
    env_file:
      - .env


volumes:
  osintbuddy-db-data:
  sdb-data:
  solr-data:
